# Análise com regras recomendadas da comunidade
include: package:dart_code_metrics_presets/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.mocks.dart"

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
    source-lines-of-code: 100
    number-of-methods: 10

  rules-exclude:
    - test/**
    - build/**
    - lib/generated/**
  
  rules:
    - avoid-non-null-assertion
    - prefer-trailing-comma
    - avoid-unused-parameters
    - no-equal-then-else
    - avoid-returning-widgets
    - prefer-extracting-callbacks

linter:
  rules:
    prefer_single_quotes: true
