name: filely
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider:
  shared_preferences: 
  percent_indicator:
  mime_type: ^1.0.1
  path: 
#  thumbnails: ^1.0.1
  path_provider:
  fluttertoast: 
  permission_handler: ^12.0.1
  intl: 
  open_file:
  video_player: ^2.10.0
  isolate_handler: ^1.0.2
  installed_apps: ^1.6.0
  device_info_plus: ^11.5.0
  # disk_space: ^0.2.1
  disk_space_plus: ^0.2.6
  flex_color_scheme: ^8.2.0
  google_fonts: ^6.2.1
  timeago: ^3.7.1
  share_plus: ^11.0.0
  just_audio: ^0.10.4
  audio_session: ^0.2.2
  audio_service: ^0.18.18
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  dart_code_metrics_presets: ^2.24.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

