name: filely
description: A modern and powerful Flutter file explorer.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # File & Media Handling
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  file_picker: ^10.1.7
  open_file: ^3.5.10
  flutter_file_dialog: ^3.0.2
  flutter_image_compress: ^2.1.0
  image: ^4.1.4
  video_player: ^2.9.5

  # Device Info
  device_info_plus: ^11.4.0
  just_audio: ^0.10.2
  audio_session: ^0.2.1
  audio_service: ^0.18.18
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  rxdart: ^0.28.0
  flex_color_scheme: ^8.2.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for good practices
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment and add your assets here:
  # assets:
  #   - assets/images/
  #
  # Uncomment and define custom fonts here:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
